apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: chat-be
  namespace: ai-agent-platform
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: chat-be
  namespaceSelector:
    matchNames:
      - ai-agent-platform
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
