{{- if .Values.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.existingSecret }}
type: Opaque
stringData:
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | quote }}
  {{- if .Values.secrets.googleApiKey }}
  GOOGLE_API_KEY: {{ .Values.secrets.googleApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.openweatherApiKey }}
  OPENWEATHER_API_KEY: {{ .Values.secrets.openweatherApiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.alphavantageApiKey }}
  ALPHAVANTAGE_API_KEY: {{ .Values.secrets.alphavantageApiKey | quote }}
  {{- end }}
{{- end }}
