apiVersion: v1
kind: Service
metadata:
  name: {{ include "mcp-server.fullname" . }}
  labels:
    {{- include "mcp-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "mcp-server.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      name: http
      targetPort: {{ .Values.containerPort }}
